apiVersion: push.aerogear.org/v1alpha1
kind: UnifiedPushServer
metadata:
  name: example-unifiedpushserver
spec:
  useMessageBroker: false
  externalDB: false
  databaseHost: example-host
  databaseName: example-name
  databasePassword: password
  databaseUser: user
  databasePort: '5432'