---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: unifiedpush-operator
subjects:
- kind: ServiceAccount
  name: unifiedpush-operator
  namespace: unifiedpush
roleRef:
  kind: Role
  name: unifiedpush-operator
  apiGroup: rbac.authorization.k8s.io
