apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring-key: middleware
  name: unifiedpush-operator
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      name: unifiedpush-operator
