# Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    monitoring-key: middleware
    prometheus: application-monitoring
    role: alert-rules
  name: unifiedpush
spec:
  selector:
    matchLabels:
      app: unifiedpush
  groups:
    - name: general.rules
      rules:
      - alert: UnifiedpushDown
        expr: absent(kube_pod_container_status_running{namespace="unifiedpush",container="ups"}==1)
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "The UnifiedPush Pod Server has been down for more than 5 minutes. "
          summary: "The UnifiedPush Pod Server is down. For more information see on the UnifiedPush at https://github.com/aerogear/aerogear-unifiedpush-server"
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushConsoleDown
        expr: absent(kube_endpoint_address_available{endpoint="example-unifiedpushserver-unifiedpush"} == 1)
        for: 5m
        labels:
          severity: critical
        annotations:
          description: "The UnifiedPush admin console has been down for more than 5 minutes. "
          summary: "The UnifiedPush admin console endpoint has been unavailable for more that 5 minutes. For more information see on the UnifiedPush  at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushDatabaseDown
        expr: absent(kube_pod_container_status_running{namespace="unifiedpush",container="postgresql"}==1)
        for: 5m
        labels: 
          severity: critical
        annotations:
          description: "The UnifiedPush Database pod has been down for more than 5 minutes"
          summary: "The UnifiedPush Database is down. For more information see on the UnifiedPush at https://github.com/aerogear/aerogear-unifiedpush-serve"
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushPodCPUHigh # todo check if it will work after expse the metrcis
        expr: "(rate(process_cpu_seconds_total{job='example-unifiedpushserver-unifiedpush'}[1m])) > (((kube_pod_container_resource_limits_cpu_cores{namespace='mobile-security-service',container='application'})/100)*90)"
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "The UnifiedPush Server Pod has been at 90% CPU usage for more than 5 minutes"
          summary: "The UnifiedPush Server Pod is reporting high cpu usage for more that 5 minutes. For more information see on the UnifiedPush  at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushPodMemoryHigh # todo check if it will work after expse the metrcis
        expr: "(process_resident_memory_bytes{job='example-unifiedpushserver-unifiedpush'}) > (((kube_pod_container_resource_limits_memory_bytes{namespace='unifiedpush',container='ups'})/100)*90)"
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "The UnifiedPush API has been at 90% memory usage for more than 5 minutes"
          summary: "The UnifiedPush API is reporting high memory usage for more that 5 minutes. For more information see on the UnifiedPush  at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushApiHighRequestDuration # todo expose metric
        expr: "api_requests_duration_seconds{job='example-unifiedpushserver-unifiedpush', quantile='0.5'} > 30"
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "The UnifiedPush API has had http requests latency longer that 30 seconds for more than 5 minutes"
          summary: "The UnifiedPush API is reporting high request latency for more that 5 minutes. For more information see on the UnifiedPush  at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushApiHighRequestHighConcurrentRequests # todo expose metric
        expr: "api_requests_in_flight{job='example-unifiedpushserver-unifiedpush'} > 50"
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "The UnifiedPush API has had 50 concurrent requests for more than 5 minutes"
          summary: "The UnifiedPush API is reporting high request concurrency for more that 5 minutes. For more information see on the UnifiedPush  at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushApHighRequestFailure # todo expose metric
        expr: "rate(api_requests_failure_total{job='example-unifiedpushserver-unifiedpush'}[1h])>10"
        for: 1h
        labels:
          severity: warning
        annotations:
          description: "The UnifiedPush API has reported more that 10 request failures in an hour"
          summary: "The UnifiedPush API is reporting a high request failure over an hour. For more information see on the UnifiedPush ServerServer at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert:  UnifiedPushJavaHeapThresholdExceeded
        expr: |
          100 * jvm_memory_bytes_used{area="heap",namespace="unifiedpush"}
            / jvm_memory_bytes_max{area="heap",namespace="unifiedpush"}
            > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "The Heap Usage of the UnifiedPush Server exceeded 90% of usage"
          summary: "The UnifiedPush Server JVM Heap Threshold Exceeded 90% of usage. For more information see on the UnifiedPush Server at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushJavaHeapThresholdExceeded
        expr: |
          100 * jvm_memory_bytes_used{area="heap",namespace="unifiedpush"}
            / jvm_memory_bytes_max{area="heap",namespace="unifiedpush"}
            > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "The heap usage of the UnifiedPush Server exceeded 90% of usage"
          summary: "The heap usage of the UnifiedPush Server exceeded 90% of usage. For more information see on the UnifiedPush Server at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushJavaNonHeapThresholdExceeded
        expr: |
          100 * jvm_memory_bytes_used{area="nonheap",namespace="unifiedpush"}
            / jvm_memory_bytes_max{area="nonheap",namespace="unifiedpush"}
            > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "The nonheap usage of the UnifiedPush Server exceeded 90% of usage"
          summary: "The nonheap usage of the UnifiedPush Server exceeded 90% of usage .For more information see on the UnifiedPush Server at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushJavaGCTimePerMinuteScavenge
        expr: |
          increase(jvm_gc_collection_seconds_sum{gc="PS Scavenge",namespace="unifiedpush"}[1m]) > 1 * 60 * 0.9
        for: 1m
        labels:
          severity: critical
        annotations:
          description: "Amount of time per minute spent on garbage collection in the UnifiedPush Server pod exceeds 90%"
          summary: "Amount of time per minute spent on garbage collection in the UnifiedPush Server pod exceeds 90%. This could indicate that the available heap memory is insufficient..For more information see on the UnifiedPush Server at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushJavaDeadlockedThreads
        expr: |
          jvm_threads_deadlocked{namespace="unifiedpush"}
            > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          description: "Number of threads in deadlock state of the UnifiedPush Server > 0"
          summary: "Number of threads in deadlock state of the UnifiedPush Server > 0.For more information see on the UnifiedPush Server at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo
      - alert: UnifiedPushMessagesFailures # todo expose metric
        expr: >
          rate(ups_msg_fails_total{namespace="unifiedpush"}[5m])
          * 300 > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "More than 50 failed messages attempts for UnifiedPush Server fails over the last 5 minutes."
          summary: "More than 50 failed messages attempts for UnifiedPush Server fails over the last 5 minutes. For more information see on the UnifiedPush Server at https://github.com/aerogear/UnifiedPush "
          sop_url: "https://github.com/aerogear/unifiedpush-operator/blob/0.1.0/SOP/SOP-push.adoc" #todo