# Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring-key: middleware
  name: unifiedpush
spec:
  endpoints:
    - path: /rest/prometheus/metrics
      port: web
  selector:
    matchLabels:
      internal: unifiedpush